(function () {
  'use strict';

  const ROOT_ID = '__vn_ext_root__';
  if (document.getElementById(ROOT_ID)) return;

  // ── Vocabulary data (auto-generated by build_extension.py) ───
  const VOCAB = __VOCAB_DATA__;

  // ── Category colors ───────────────────────────────────────────
  const COLORS = {
    'Verbo':         { bg: '#dbeafe', tx: '#1d4ed8' },
    'Substantivo':   { bg: '#d1fae5', tx: '#065f46' },
    'Adjetivo':      { bg: '#fce7f3', tx: '#9d174d' },
    'Adv\u00e9rbio': { bg: '#fef3c7', tx: '#92400e' },
    'Pronome':       { bg: '#ede9fe', tx: '#5b21b6' },
    'Express\u00e3o':{ bg: '#ffedd5', tx: '#9a3412' },
    'Sauda\u00e7\u00e3o': { bg: '#ecfdf5', tx: '#065f46' },
    'Part\u00edcula':{ bg: '#f0f9ff', tx: '#0369a1' },
    'Interrogativo': { bg: '#fff7ed', tx: '#c2410c' },
    'Conjun\u00e7\u00e3o': { bg: '#f5f3ff', tx: '#4c1d95' },
    'Demonstrativo': { bg: '#fef2f2', tx: '#991b1b' },
    'Classificador': { bg: '#f0fdf4', tx: '#166534' },
    'Confirma\u00e7\u00e3o': { bg: '#dcfce7', tx: '#14532d' },
    'Profiss\u00e3o': { bg: '#fffbeb', tx: '#78350f' },
    'Nome':          { bg: '#fdf4ff', tx: '#701a75' },
    'N\u00famero':   { bg: '#eff6ff', tx: '#1e40af' },
    'Modal':         { bg: '#fef9c3', tx: '#713f12' },
    'Preposi\u00e7\u00e3o': { bg: '#f1f5f9', tx: '#334155' },
    'Interjei\u00e7\u00e3o': { bg: '#fff1f2', tx: '#881337' },
  };

  // ── Persistent state ──────────────────────────────────────────
  const SK = '__vn_ov__';
  let isOpen = false, isMin = false, isPinned = false;
  let cat = 'Todos', q = '';
  let pos = { x: Math.max(10, window.innerWidth - 440), y: 80 };

  try {
    const s = JSON.parse(localStorage.getItem(SK) || '{}');
    if (typeof s.x === 'number') pos = { x: s.x, y: s.y };
    if (s.pinned) isPinned = true;
  } catch {}

  const save = () => {
    try { localStorage.setItem(SK, JSON.stringify({ x: pos.x, y: pos.y, pinned: isPinned })); } catch {}
  };

  // ── Shadow DOM host ───────────────────────────────────────────
  const host = document.createElement('div');
  host.id = ROOT_ID;
  host.style.cssText = 'all:initial;position:fixed!important;z-index:2147483647!important;top:0!important;left:0!important;width:0!important;height:0!important;overflow:visible!important;';

  const attach = () => { (document.body || document.documentElement).appendChild(host); };
  if (document.body) attach();
  else document.addEventListener('DOMContentLoaded', attach);

  let shadow;
  try { shadow = host.attachShadow({ mode: 'open' }); }
  catch { return; } // page doesn't allow shadow DOM

  // ── Styles ────────────────────────────────────────────────────
  const style = document.createElement('style');
  style.textContent = `
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    #pnl {
      position: fixed; width: 400px;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      font-size: 14px; color: #0f172a;
      background: #ffffff; border: 1.5px solid #e2e8f0;
      border-radius: 12px; box-shadow: 0 20px 60px rgba(0,0,0,0.28);
      display: flex; flex-direction: column; overflow: hidden;
    }
    #pnl.pinned { border: 2px solid #4f46e5; }
    #hdr {
      background: #4f46e5; padding: 9px 12px;
      display: flex; align-items: center; gap: 6px;
      cursor: grab; user-select: none; flex-shrink: 0;
    }
    #hdr:active { cursor: grabbing; }
    #pnl.pinned #hdr { background: #3730a3; cursor: default; }
    #ttl { font-size: 13px; font-weight: 700; color: #fff; flex: 1; }
    .hb {
      background: rgba(255,255,255,0.2); border: none; color: #fff;
      cursor: pointer; border-radius: 5px; padding: 3px 8px;
      font-size: 12px; font-weight: 700; flex-shrink: 0; line-height: 1.4;
    }
    .hb:hover { background: rgba(255,255,255,0.35); }
    .hb.x { background: rgba(200,0,0,0.45); }
    .hb.x:hover { background: rgba(220,0,0,0.65); }
    #bdy {
      display: flex; flex-direction: column; gap: 8px;
      padding: 10px 12px 12px;
      max-height: min(500px, calc(100vh - 120px)); overflow: hidden;
    }
    #si {
      width: 100%; padding: 7px 12px; font-size: 13px; font-family: inherit;
      border: 1.5px solid #e2e8f0; border-radius: 9999px;
      background: #f8fafc; color: #0f172a; outline: none;
    }
    #si:focus { border-color: #818cf8; background: #fff; }
    #cats {
      display: flex; gap: 4px; overflow-x: auto;
      padding-bottom: 2px; scrollbar-width: none; flex-shrink: 0;
    }
    #cats::-webkit-scrollbar { display: none; }
    .cb {
      padding: 2px 8px; border-radius: 9999px; border: 1.5px solid #e2e8f0;
      background: #fff; color: #64748b; font-size: 10.5px; font-family: inherit;
      cursor: pointer; white-space: nowrap; flex-shrink: 0;
    }
    .cb.on { background: #4f46e5; color: #fff; border-color: #4f46e5; }
    #cnt { font-size: 11px; color: #94a3b8; flex-shrink: 0; }
    #res { overflow-y: auto; flex: 1; border: 1px solid #f1f5f9; border-radius: 8px; }
    table { width: 100%; border-collapse: collapse; font-size: 12.5px; }
    thead th {
      text-align: left; padding: 6px 10px; font-size: 10px;
      font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em;
      color: #94a3b8; border-bottom: 2px solid #e2e8f0; background: #f8fafc;
      position: sticky; top: 0; z-index: 1;
    }
    tbody tr { border-bottom: 1px solid #f1f5f9; cursor: default; }
    tbody tr:last-child { border-bottom: none; }
    tbody tr:hover td { background: #f0f4ff; }
    td { padding: 6px 10px; vertical-align: middle; }
    .vn { font-weight: 700; color: #4f46e5; }
    .badge {
      display: inline-block; padding: 2px 6px; border-radius: 9999px;
      font-size: 10px; font-weight: 600; white-space: nowrap;
    }
    #more { text-align: center; padding: 8px; font-size: 11px; color: #94a3b8; }
  `;
  shadow.appendChild(style);

  // ── Panel DOM ─────────────────────────────────────────────────
  const pnl = document.createElement('div');
  pnl.id = 'pnl';
  if (isPinned) pnl.classList.add('pinned');
  shadow.appendChild(pnl);

  pnl.innerHTML = `
    <div id="hdr">
      <span id="ttl">📚 Vocabulário VN</span>
      <button class="hb" id="bpin" title="Fixar posição">📍</button>
      <button class="hb" id="bmin" title="Minimizar">▼</button>
      <button class="hb x" id="bcls" title="Fechar (Ctrl+Shift+V)">✕</button>
    </div>
    <div id="bdy">
      <input id="si" type="text" placeholder="Buscar: vietnamita, português ou inglês..." autocomplete="off" spellcheck="false" />
      <div id="cats"></div>
      <div id="cnt"></div>
      <div id="res">
        <table>
          <thead><tr><th>Vietnamita</th><th>Português</th><th>Cat.</th></tr></thead>
          <tbody id="tb"></tbody>
        </table>
        <div id="more"></div>
      </div>
    </div>
  `;

  const $ = (id) => shadow.getElementById(id);
  const bdy = $('bdy'), si = $('si'), catsEl = $('cats');
  const cnt = $('cnt'), tb = $('tb'), more = $('more');
  const bpin = $('bpin'), bmin = $('bmin'), bcls = $('bcls');
  const hdr = $('hdr');

  // ── Category buttons ──────────────────────────────────────────
  const allCats = ['Todos', ...[...new Set(VOCAB.map(v => v.c))].sort()];
  allCats.forEach(c => {
    const b = document.createElement('button');
    b.className = 'cb' + (c === cat ? ' on' : '');
    b.textContent = c;
    b.addEventListener('click', () => { cat = c; renderCats(); renderRows(); });
    catsEl.appendChild(b);
  });

  function renderCats() {
    catsEl.querySelectorAll('.cb').forEach((b, i) => b.classList.toggle('on', allCats[i] === cat));
  }

  function renderRows() {
    const ql = q.toLowerCase();
    const filtered = VOCAB.filter(v => {
      const mq = !ql || v.v.toLowerCase().includes(ql) || v.p.toLowerCase().includes(ql) || (v.e && v.e.toLowerCase().includes(ql));
      return mq && (cat === 'Todos' || v.c === cat);
    });

    cnt.textContent = `${filtered.length} resultado${filtered.length !== 1 ? 's' : ''}`;
    tb.innerHTML = '';

    filtered.slice(0, 120).forEach(v => {
      const col = COLORS[v.c] || { bg: '#f1f5f9', tx: '#475569' };
      const tr = document.createElement('tr');
      tr.innerHTML = `
        <td class="vn">${v.v}</td>
        <td>${v.p}</td>
        <td><span class="badge" style="background:${col.bg};color:${col.tx}">${v.c}</span></td>
      `;
      if (v.g) tr.title = v.g;
      tb.appendChild(tr);
    });

    more.textContent = filtered.length > 120 ? `+${filtered.length - 120} resultados — refine a busca` : '';
  }

  // ── Position / drag ───────────────────────────────────────────
  const applyPos = () => {
    pnl.style.left = Math.max(0, Math.min(pos.x, window.innerWidth  - 410)) + 'px';
    pnl.style.top  = Math.max(0, Math.min(pos.y, window.innerHeight -  60)) + 'px';
  };
  applyPos();

  let drag = null;
  hdr.addEventListener('mousedown', e => {
    if (isPinned || e.button !== 0) return;
    e.preventDefault(); e.stopPropagation();
    drag = { mx: e.clientX, my: e.clientY, px: pos.x, py: pos.y };
  });
  document.addEventListener('mousemove', e => {
    if (!drag) return;
    pos.x = drag.px + (e.clientX - drag.mx);
    pos.y = drag.py + (e.clientY - drag.my);
    applyPos();
  }, true);
  const stopDrag = () => { if (drag) { drag = null; save(); } };
  document.addEventListener('mouseup', stopDrag, true);
  window.addEventListener('blur', stopDrag);

  // ── Open / close / minimize / pin ────────────────────────────
  function setOpen(v) {
    isOpen = v;
    pnl.style.display = v ? 'flex' : 'none';
    if (v) { renderRows(); setTimeout(() => si.focus(), 60); }
  }
  function setMin(v) {
    isMin = v;
    bdy.style.display = v ? 'none' : 'flex';
    bmin.textContent = v ? '▲' : '▼';
  }
  function setPin(v) {
    isPinned = v;
    pnl.classList.toggle('pinned', v);
    bpin.textContent = v ? '📌' : '📍';
    bpin.title = v ? 'Desafixar (pode arrastar)' : 'Fixar posição';
    save();
  }

  bcls.addEventListener('click', e => { e.stopPropagation(); setOpen(false); });
  bmin.addEventListener('click', e => { e.stopPropagation(); setMin(!isMin); });
  bpin.addEventListener('click', e => { e.stopPropagation(); setPin(!isPinned); });
  si.addEventListener('input', e => { q = e.target.value; renderRows(); });

  // ── Keyboard shortcut (Ctrl+Shift+V) ─────────────────────────
  document.addEventListener('keydown', e => {
    if (e.ctrlKey && e.shiftKey && (e.key === 'V' || e.key === 'v')) {
      e.preventDefault(); e.stopPropagation();
      setOpen(!isOpen);
    }
  }, true);

  // ── Chrome extension icon click (via background.js message) ──
  if (typeof chrome !== 'undefined' && chrome.runtime && chrome.runtime.onMessage) {
    chrome.runtime.onMessage.addListener(msg => {
      if (msg && msg.action === 'toggle') setOpen(!isOpen);
    });
  }

  // Start closed
  setOpen(false);
})();
